export TF_VAR_ldbws_token        = $(LDBWS_TOKEN)
export TF_VAR_station_crs        = $(STATION_CRS)
export TF_VAR_clean_bucket       = $(CLEAN_BUCKET)
export TF_VAR_glue_scripts_bucket = $(GLUE_SCRIPTS_BUCKET)
export TF_VAR_region             = $(REGION)
export TF_VAR_glue_database      = $(GLUE_DATABASE)
export TF_VAR_glue_table         = $(GLUE_TABLE)
